name: Docker

on:
  push:
    branches:
      - main
    tags:
      - '*.*.*'
  schedule:
    - cron: '45 19 * * *' # randcron

jobs:
  image:
    uses: edencehealth/workflows/.github/workflows/dockerimage.yml@main
    with:
      container_name: rcore
      push_readme: README.md
    secrets: inherit
