name: Docker

on:
  push:
    branches:
      - main
    tags:
      - '*.*.*'

jobs:
  image:
    uses: edencehealth/workflows/.github/workflows/dockerimage.yml@v1
    with:
      container_name: rcore
    secrets: inherit
